name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libnss3 libxkbfile1 libgconf-2-4 libxrandr2 libgtk-3-0 libxss1 libasound2

      - name: Run tests
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run --auto-servernum -- npm run package
            xvfb-run --auto-servernum -- npm run lint
            xvfb-run --auto-servernum -- npm exec tsc
            xvfb-run --auto-servernum -- npm test
          else
            npm run package
            npm run lint
            npm exec tsc
            npm test
          fi
